name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Install mysql
      run: |
        sudo apt-get update
        sudo apt-get -y install mysql-server libmysqlclient-dev
        sudo /etc/init.d/mysql start
        mysql -e "create database holla; grant all on \`holla%\`.* to 'root'@'localhost';" -uroot -proot
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout holla
      uses: actions/checkout@v2
      with:
        path: vlib/holla
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V Doctor
      run: |
        v doctor
    - name: Build tests
      run: |
        cd ./vlib/holla/
        mysql -e "SHOW TABLES" -uroot -proot holla || echo down
        v -cg test mysql_test.v
