name: CI

on: [push, pull_request]

jobs:
#  ubuntu:
#    runs-on: ubuntu-20.04
#    steps:
#    - name: Install mysql
#      run: |
#        sudo apt-get update
#        sudo apt-get -y install mysql-server libmysqlclient-dev
#        sudo /etc/init.d/mysql start
#        mysql -e "create database holla; grant all on \`holla%\`.* to 'root'@'localhost';" -uroot -proot
#    - name: Install postgres
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libpq-dev postgresql
#        echo "host    all             all             127.0.0.1/32            md5" > sudo tee -a /etc/postgresql/10/main/pg_hba.conf
#        sudo service postgresql restart && sleep 3
#        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
#        sudo -u postgres createdb holla
#        sudo service postgresql restart && sleep 3
#    - name: Install sqlite
#      run: |
#        sudo apt-get install -y libssl-dev sqlite3 libsqlite3-dev
#    - name: Checkout V
#      uses: actions/checkout@v2
#      with:
#        repository: vlang/v
#    - name: Checkout holla
#      uses: actions/checkout@v2
#      with:
#        path: vlib/holla
#    - name: Build V
#      run: |
#        make
#        sudo ./v symlink
#    - name: V Doctor
#      run: |
#        v doctor
#    - name: Build tests
#      run: |
#        cd ./vlib/holla/
#        v -cg test .
#
#  macos:
#    runs-on: macos-latest
#    steps:
#    - name: Install mysql
#      run: |
#        # brew uninstall openssl@1.0.2t
#        # brew uninstall python@2.7.17
#        # brew untap local/openssl
#        # brew untap local/python2
#        # brew cask install xquartz
#        brew update
#        brew install mysql
#        brew install mysql-client
#        brew services start mysql
#        brew services stop mysql;sleep 3;brew services start mysql
#        sleep 2
#        macos_mysql_version="$(ls /usr/local/Cellar/mysql)"
#        /usr/local/Cellar/mysql/${macos_mysql_version}/bin/mysql -e "create database holla; grant all on \`holla%\`.* to 'root'@'localhost';" -uroot
#    - name: Install postgres
#      run: |
#        /usr/local/opt/postgres/bin/pg_ctl -D /usr/local/var/postgres start
#        sleep 3
#        /usr/local/opt/postgres/bin/createuser -s postgres
#        /usr/local/opt/postgres/bin/createdb holla -U postgres
#    - name: Install sqlite
#      run: |
#        # brew uninstall openssl@1.0.2t
#        # brew uninstall python@2.7.17
#        # brew untap local/openssl
#        # brew untap local/python2
#        # brew cask install xquartz
#        brew update
#        brew install sqlite
#    - name: Checkout V
#      uses: actions/checkout@v2
#      with:
#        repository: vlang/v
#    - name: Checkout holla
#      uses: actions/checkout@v2
#      with:
#        path: vlib/holla
#    - name: Build V
#      run: |
#        make
#        ./v symlink
#    - name: Build tests
#      run: |
#        cd ./vlib/holla/
#        v -cg test .

  windows-msvc:
    runs-on: windows-latest
    env:
        VFLAGS: -cc msvc
    steps:
    - name: Install sqlite
      shell: cmd
      run: |
        choco install sqlite
        curl -L https://www.sqlite.org/2020/sqlite-amalgamation-3320300.zip -o sqlite-amalgamation-3320300.zip
        unzip sqlite-amalgamation-3320300.zip -d thirdparty\
        del thirdparty\sqlite-amalgamation-3320300\shell.c
        move /y thirdparty\sqlite-amalgamation-3320300  thirdparty\sqlite
        dir thirdparty\sqlite
    - name: Install postgres
      shell: bash
      run: |
        choco install postgresql12 --force --params '/Password:postgres'
    - name: Install mysql
      shell: cmd
      run: |
          choco install mysql
          "C:\tools\mysql\current\bin\mysql" -e "create database holla; grant all on `holla%`.* to 'root'@'localhost';" -uroot
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout holla
      uses: actions/checkout@v2
      with:
        path: vlib/holla
    - name: Build V
      run: .\make.bat -msvc
    - name: Build tests
      run: .\v.exe test .\vlib\holla\.