name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Install mysql
      run: |
        sudo apt-get update
        sudo apt-get -y install mysql-server libmysqlclient-dev
        sudo /etc/init.d/mysql start
        mysql -e "create database holla; grant all on \`holla%\`.* to 'root'@'localhost';" -uroot -proot
    - name: Install postgres
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev postgresql
        echo "host    all             all             127.0.0.1/32            md5" > sudo tee -a /etc/postgresql/10/main/pg_hba.conf
        sudo service postgresql restart && sleep 3
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
        sudo -u postgres createdb holla
        sudo service postgresql restart && sleep 3
    - name: Install sqlite
      run: |
        apt-get install --quiet -y libssl-dev sqlite3 libsqlite3-dev
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout holla
      uses: actions/checkout@v2
      with:
        path: vlib/holla
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V Doctor
      run: |
        v doctor
    - name: Build tests
      run: |
        cd ./vlib/holla/
        v -cg test .
